AWSTemplateFormatVersion: '2010-09-09'
Transform: 'AWS::Serverless-2016-10-31'
Description: AWS AI RAG project
Parameters:
  stackName:
    Description: The stack or project name
    Type: String
    MinLength: 1
    MaxLength: 50
  timePeriodValue:
    Description: "The time period of the scheduled scrape event (without unit)"
    Type: Number
    MinValue: 1
    MaxValue: 255
  timePeriodUnit:
    Description: "The unit for the time period of the scheduled event, e.g. 'minute'"
    Type: String
    MinLength: 1
    MaxLength: 50
  timeout:
    Description: Timeout in seconds for the lambdas
    Type: Number
    MinValue: 1
    Default: 180
  logLevel:
    Description: The log level for the lambda functions, e.g. DEBUG
    Type: String
    MinLength: 1
    MaxLength: 50
    Default: INFO

Resources:

  ossDomain:
    Type: AWS::OpenSearchService::Domain
    Properties:
      DomainName:
        !Join
        - '-'
        - - !Ref stackName
          - 'oss-domain'
      EngineVersion: OpenSearch_2.13
      EBSOptions:
        EBSEnabled: true
        VolumeSize: 10
        VolumeType: standard
      ClusterConfig:
        InstanceCount: 1
        InstanceType: t2.small.search
      AccessPolicies:
        Version: '2012-10-17'
        Statement:
          -
            Effect: 'Allow'
            Principal:
              AWS: !Ref "AWS::AccountId"
            Action: 'es:*'
            Resource: !Sub 'arn:aws:es:${AWS::Region}:${AWS::AccountId}:domain/${stackName}-oss-domain/*'

  mainScrapeLog:
    Type: AWS::Logs::LogGroup
    Properties:
      LogGroupClass: STANDARD
      RetentionInDays: 3
      LogGroupName:
        !Join
        - '-'
        - - !Ref stackName
          - 'lambda-main-scrape-log'

  accessPolicyToSQS:
    Type: AWS::IAM::ManagedPolicy
    Properties:
      Description: Allow writing to SQS
      PolicyDocument:
        Version: "2012-10-17"
        Statement:
          - Effect: Allow
            Action: 'sqs:SendMessage'
            Resource: !GetAtt queue.Arn

  mainScrape:
    Type: AWS::Serverless::Function
    Properties:
      Environment:
        Variables:
          SQS_URL: !GetAtt queue.QueueUrl
          LOG_LEVEL: !Ref logLevel
      FunctionName:
        !Join
        - '-'
        - - !Ref stackName
          - 'lambda-main-scrape'
      Architectures:
        - x86_64
      MemorySize: 128
      PackageType: Zip
      Handler: main_scrape_lambda.lambda_function.lambda_handler
      Runtime: python3.10
      CodeUri: .
      Description: Do a periodic scrape of the main page
      Timeout: !Ref timeout
      Policies:
        - AWSLambdaBasicExecutionRole
        - AWSLambda_ReadOnlyAccess
        - !Ref accessPolicyToSQS
      Layers:
        - Ref: libScrape
      Events:
        ScheduledEvent:
          Type: ScheduleV2
          Description: Repeating trigger for the Lambda
          Properties:
            State: ENABLED
            RetryPolicy:
              MaximumRetryAttempts: 2
              MaximumEventAgeInSeconds: 240
            ScheduleExpression:
              !Join
              - ''
              - - 'rate('
                - !Ref timePeriodValue
                - ' '
                - !Ref timePeriodUnit
                - ')'
            Name:
              !Join
              - '-'
              - - !Ref stackName
                - 'schedule'
      LoggingConfig:
        LogFormat: Text
        LogGroup: !Ref mainScrapeLog

  libScrape:
    Type: AWS::Serverless::LayerVersion
    Properties:
      LayerName:
        !Join
        - '-'
        - - !Ref stackName
          - 'layer'
      Description: Python packages used by the lambdas.
      ContentUri: package
      CompatibleArchitectures:
        - x86_64
      CompatibleRuntimes:
        - python3.10

  newsScrapeLog:
    Type: AWS::Logs::LogGroup
    Properties:
      LogGroupClass: STANDARD
      RetentionInDays: 3
      LogGroupName:
        !Join
        - '-'
        - - !Ref stackName
          - 'lambda-news-scrape-log'

  queue:
    Type: AWS::SQS::Queue
    Properties:
      MessageRetentionPeriod: 43200
      QueueName:
        !Join
        - '-'
        - - !Ref stackName
          - 'queue'
      RedriveAllowPolicy:
        redrivePermission: denyAll
      RedrivePolicy:
        deadLetterTargetArn: !GetAtt DLQ.Arn
        maxReceiveCount: 3
      VisibilityTimeout:
        # Make this 10x the lambda timeout
        !Join
        - ''
        - - !Ref timeout
          - '0'

  DLQ:
    Type: AWS::SQS::Queue
    Properties:
      MessageRetentionPeriod: 432000
      QueueName:
        !Join
        - '-'
        - - !Ref stackName
          - 'dlq'

  newsScrape:
    Type: AWS::Serverless::Function
    Properties:
      Environment:
        Variables:
          OSS_CLUSTER_URL: !GetAtt ossDomain.DomainEndpoint
          LOG_LEVEL: !Ref logLevel
      FunctionName:
        !Join
        - '-'
        - - !Ref stackName
          - 'lambda-news-scrape'
      Architectures:
        - x86_64
      MemorySize: 128
      PackageType: Zip
      Handler: news_scrape_lambda.lambda_function.lambda_handler
      Runtime: python3.10
      CodeUri: .
      Description: Read events from SQS and process
      Timeout: !Ref timeout
      Policies:
        - AWSLambdaBasicExecutionRole
        - AWSLambda_ReadOnlyAccess
        - AmazonOpenSearchServiceFullAccess
        - AmazonBedrockFullAccess
        - AWSLambdaSQSQueueExecutionRole
      Layers:
        - Ref: libScrape
      Events:
        SQSEvent:
          Type: SQS
          Description: Run the Lambda with an SQS event
          Properties:
            BatchSize: 1
            MaximumBatchingWindowInSeconds: 0
            Enabled: true
            Queue: !GetAtt queue.Arn
      LoggingConfig:
        LogFormat: Text
        LogGroup: !Ref newsScrapeLog
