name: bandit

on: [push, workflow_dispatch]

jobs:
  bandit:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.10"
      - name: Install dependencies
        run: |
          pip install bandit
      - name: bandit
        run: python -m bandit -r . --exclude=/tests/,/venv/,/old_examples/,/layer/
      - name: Save result
        if: always()
        uses: ./.github/actions/save-workflow-result
        with:
          result: ${{ job.status }}
