name: pydocstyle

on: [push, workflow_dispatch]

jobs:
  pydocstyle:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.10"
      - name: Install dependencies
        run: |
          pip install pydocstyle
      - name: pydocstyle
        run: python -m pydocstyle *.py fastapi_lambda main_scrape_lambda news_scrape_lambda query_lambda deletion_lambda --ignore=D107,D203,D213
      - name: Save result
        if: always()
        uses: ./.github/actions/save-workflow-result
        with:
          result: ${{ job.status }}

