name: pylint

on: [push, workflow_dispatch]

jobs:
  pylint:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Prepare test environment
        uses: ./.github/actions/prepare-test-environment
      - name: pylint
        run: python -m pylint *.py fastapi_lambda main_scrape_lambda news_scrape_lambda query_lambda
      - name: Save result
        if: always()
        uses: ./.github/actions/save-workflow-result
        with:
          result: ${{ job.status }}

