name: tests

on: [push, workflow_dispatch]

jobs:
  tests:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v4
    - name: Prepare test environment
      uses: ./.github/actions/prepare-test-environment
    - uses: aws-actions/configure-aws-credentials@v4
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: eu-west-2
    - name: Run dynamoDB test container
      run: |
        export DB_TABLE_NAME=testTable
        export TEST=true
        docker run --rm --name dynamodb_test_local -d -p 8000:8000 amazon/dynamodb-local
        sleep 5
        ./create_test_table.sh
    - name: tests
      run: |
        export DB_TABLE_NAME=testTable
        export TEST=true
        python -m pytest function/app tests -p no:cacheprovider
    - name: Save result
      if: always()
      uses: ./.github/actions/save-workflow-result
      with:
        result: ${{ job.status }}
